### ISSUE TITLE
Email server shutdown warning again after extending cluster

### ISSUE THREAD

**Issue by teonbrooks** [mozilla/telemetry-analysis-service#1101]
Hey, would it be possible to send another hour warning email if a user extends the cluster life?

**Comment by teonbrooks** [comment]
cc: @jezdez

**Comment by jezdez** [comment]
This seems like a good idea but I'm afraid ATMO feature development is on hold while Redash and STMO take the majority of our time. Rest assured when we get back to ATMO we'll schedule working on this.
