### ISSUE TITLE
Support SameSite cookie attribute on sessionid

### ISSUE THREAD

**Issue by psiinon** [mozilla/telemetry-analysis-service#1128]
Firefox 60 introduces support for the SameSite cookie attribute: https://blog.mozilla.org/security/2018/04/24/same-site-cookies-in-firefox-60/
This provides significant protection against CSRF vulnerabilities and so it should be applied to the sessionid cookie.
It looks like its been added to Django https://code.djangoproject.com/ticket/27863 but the fix doesnt appear the be in the latest release or on older streams.
We have various other services that are also on django 1.11.x so I'll look into whether we can get the fix back-ported to that stream.

**Comment by psiinon** [comment]
Unfortunately 1.11 is only receiving data loss and security fixes: https://code.djangoproject.com/ticket/29409 :(

**Comment by jezdez** [comment]
Django 2.1 is [out in August](https://code.djangoproject.com/wiki/Version2.1Roadmap), which fits well the timeframe to work on ATMO again. I don't think this should be tried to be implemented as a 3rd party app right now given the non-trivial [implementation of the patch](https://github.com/django/django/pull/9860/files).

**Comment by jezdez** [comment]
@psiinon Just saw a bunch of Django sites have been asked to do this, please make sure we use the same solution in the interim to 2.1.

**Comment by psiinon** [comment]
@jezdez yes, pontoon are looking to support this via middleware: https://github.com/mozilla/pontoon/pull/964
I'm hoping this will be a common solution that other apps can use as well.

**Comment by jotes** [comment]
I talked with at IRC @psiinon the plan is to create a small Django package with this middleware and push it to Pypi today.

**Comment by jezdez** [comment]
@jotes Thanks for releasing this as an app!
