### ISSUE TITLE
FYI: Renovate will auto open PRs for vulnerabilities on 2018-08-08

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/telemetry-analysis-service#1220]
This repository uses the GitHub App Renovate.

The App has asked for additional permissions in order to open PRs for vulnerability reports automatically.

If you are concerned that such PRs will advertise a security vulnerability in this repository, you must take action to disable this new feature.

See [this bug comment][bug] for information on disabling the new feature.

--[GitHub Owners][github_owners]

[github_owners]: https://wiki.mozilla.org/GitHub
[bug]: https://bugzilla.mozilla.org/show_bug.cgi?id=1479481#c2

**Comment by jezdez** [comment]
Thanks for openening the issue.

Releasing updates of this repo are quite straight forward, so I don't think it'll be a big risk of showing the vulnerable dependencies here. Our goal is to follow the notifications and release them as soon as they show up.
