### ISSUE TITLE
Cluster Launch Error: c7043d81027f4e6b908c8147c68e723e

### ISSUE THREAD

**Issue by benmiroglio** [mozilla/telemetry-analysis-service#259]
I can't seem to launch a 15 node cluster on EMR 4.5.0 after repeated (~10) attempts.

**Comment by jezdez** [comment]
@benmiroglio We deployed a new version just now and this seems like a regression. We're working on restoring the service. Thanks for your patience!

**Comment by robhudson** [comment]
The fix for this in 6292c251af85f026d8072a40f44f5d142455996c and 8bbadd9f22be97640edfa7ac8769f6acaf512538 and has been deployed to production.
