### ISSUE TITLE
Jobs that import get_clients_history are failing

### ISSUE THREAD

**Issue by vitillo** [mozilla/telemetry-analysis-service#268]
This bug affects the following jobs:
- [ ] blok_daily
- [ ] vtabs_daily
- [ ] minvid_daily jobs 
- [x] rrayborn-telemetry-scheduled-task jobs

Please don't import `get_clients_history` as it has been deprecated.

```
...
    ImportErrorTraceback (most recent call last)

    <ipython-input-1-6f10b76290d8> in <module>()
          7 from datetime import datetime as dt, timedelta, date
          8 
    ----> 9 from moztelemetry import get_pings, get_pings_properties, get_one_ping_per_client, get_clients_history, get_records
         10 
         11 get_ipython().magic(u'pylab inline')


    ImportError: cannot import name get_clients_history
...
```

cc @ilanasegall, @sunahsuh, @rayborn, @maurodoglio

**Comment by jezdez** [comment]
@vitillo Do you want me to coordinate with job authors or just fix the notebooks myself? The alternative to `get_clients_history` is using the `Dataset` API directly, right?

**Comment by vitillo** [comment]
@jezdez please coordinate with @maurodoglio as he was taking care of that last week.

**Comment by jezdez** [comment]
@vitillo Will do, thanks.

**Comment by mreid-moz** [comment]
per @maurodoglio's advice, the recommended action is to replace the use of `get_clients_history` with the [HBaseMainSummaryView API](http://python-moztelemetry.readthedocs.io/en/stable/userguide.html#moztelemetry.hbase.HBaseMainSummaryView).

**Comment by rayborn** [comment]
Apologies for not pinging the thread back.  I had updated my script to use Datasets so I'm good to go.  Thanks!
