### ISSUE TITLE
Cluster usage page missing IP address

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/telemetry-analysis-service#272]
When I spun up a new cluster today (2017-27-02), I found that the IP address of the cluster is missing from the usage page. The address can be recovered from the aws emr console.

Attached is an image demonstrating the issue.
![image](https://cloud.githubusercontent.com/assets/3304040/23383023/62e8cfce-fcf9-11e6-8930-da301d6110cf.png)

**Comment by jezdez** [comment]
@acmiyaguchi Thanks for the report, I'll check what was going on there. This smells like another case of the AWS API throtteling us and preventing a cluster status update.

**Comment by jezdez** [comment]
Closing this for now since we've recovered from the number of queuing issues we had by increasing the time we check for new jobs to run in 31f602c.
