### ISSUE TITLE
Reduce the default cluster lifetime to 8h

### ISSUE THREAD

**Issue by maurodoglio** [mozilla/telemetry-analysis-service#298]
I believe most of the people use clusters during working hours, so defaulting to 8h seems a good approximation. This will make us save some money for those cases where the owner simply forget about the running cluster. Of course this requires #221 to be solved first, to address those special cases where the user actually wants to run a 24h (or more) long analysis.

**Comment by chutten** [comment]
Could add a field in the "launch a cluster" form that is "cluster lifetime (hours)" with a default of 8 and accepts values from 2 to 24. (like the cluster size field does from 1-30)

Especially if requesting an extension is easy (reply to the cluster termination warning email?) 8 hours might be too long of a default :)
