### ISSUE TITLE
Substitute sqlite with postgresql for heroku deployment

### ISSUE THREAD

**Issue by maurodoglio** [mozilla/telemetry-analysis-service#3]
We want to deploy a stage instance of the analysis service on heroku to verify it's working properly. Due to the ephemeral nature of heroku's nodes, we need to move away from sqlite and use the heroku-provided postgresql service.

**Comment by Uberi** [comment]
I [put one up here](https://telemetry-analysis-service.herokuapp.com/), pretty much exactly according to the instructions in the README. Note that to actually work with clusters, we'd have to use something like the following for the config settings:

```bash
heroku config:set DEBUG=True ALLOWED_HOSTS=telemetry-analysis-service.herokuapp.com, SECRET_KEY=(SECRET) AWS_ACCESS_KEY_ID=(ACCESS_KEY) AWS_SECRET_ACCESS_KEY=(SECRET_KEY)
```

At the moment, I didn't configure it with the AWS credentials, so it can't spawn or monitor any clusters.

I added you and Roberto to the app. Is there an official Mozilla Heroku account? If so, it'd probably be a good idea to transfer the app to that account.

**Comment by vitillo** [comment]
@Uberi We do have a Mozilla account. You should get in touch with @whd or @robotblake to get an account there. See also [this page](https://mana.mozilla.org/wiki/display/SVCOPS/New+Service+Guide).

**Comment by maurodoglio** [comment]
This has already been fixed
