### ISSUE TITLE
Spark cluster launches without access info on ATMO

### ISSUE THREAD

**Issue by mlopatka** [mozilla/telemetry-analysis-service#323]
After launching a cluster, page refreshes but no EMR info is displayed.

**Comment by jezdez** [comment]
Yeah, that's essential #272, I'm sorry that this is still happening. We're currently throttled when accessing AWS API to fetch the information. The info will eventually be updated and show up on the page, but after a faulty deploy yesterday we have a backlog of updates to fetch from AWS that is causing this to actually show up on your side.

I'm terribly sorry you're impacted by this, is this about https://analysis.telemetry.mozilla.org/clusters/1219/?

**Comment by jezdez** [comment]
So this has been fixed yesterday by increasing the time between job run checks in 31f602c8e2263baefae7515fad1ae3f78fe031e4.
