### ISSUE TITLE
Duplicate alert e-mails

### ISSUE THREAD

**Issue by vitillo** [mozilla/telemetry-analysis-service#353]
I have noticed some duplicate alert e-mails being sent to telemetry-alerts@m.o. For example, there are two identical e-mails for `top-signatures-correlations` on the 30th of March.

**Comment by jezdez** [comment]
Hm, I found a `java.io.FileNotFoundException: /mnt/var/log/spark/spark.log (No such file or directory)` error in container application stderr log of one of the tasks. @fbertsch Have we done any deploys of the EMR bootstrap script recently, e.g. in the past 48 hours?

**Comment by jezdez** [comment]
Closing this in favor of #417 since that has more infos for the reasons.
