### ISSUE TITLE
Add a status indicator that shows if a scheduled job is currently running

### ISSUE THREAD

**Issue by marco-c** [mozilla/telemetry-analysis-service#374]

**Comment by jezdez** [comment]
This is somewhat related to #271 which will show the job runs in a new tab of the job detail page and the "latest run" of a job in the dashboard. I can amend that feature to also show the current state of the "latest run".

**Comment by robhudson** [comment]
My plan here is to simply add a new column to the jobs list. For those with the added permission they'd get a good view of all jobs. The value of that column could either be text based of the latest run's status, possibly color coded (green for running, red for terminated with error, etc).
