### ISSUE TITLE
edit a job doesn't allow changing the ipynd

### ISSUE THREAD

**Issue by gregglind** [mozilla/telemetry-analysis-service#38]
User story:  Fixing bugs in the ipy notebook code.

Currently:  'edit job' doesn't allow changing the attached notebook.  The way to edit it to make a new job.

**Comment by jezdez** [comment]
Please file feature requests in [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Cloud%20Services&component=Metrics%3A%20Pipeline&short_desc=ATMO%20V2%3A%20&blocked=1248688)
