### ISSUE TITLE
ImportError: No module named boto3

### ISSUE THREAD

**Issue by marco-c** [mozilla/telemetry-analysis-service#381]
My notebook failed yesterday with this error.

**Comment by jezdez** [comment]
This seems like a transient error that was triggered by the EMR bootstrap script not being able to download Python packages from PyPI. I know that @robotblake has a ticket open somewhere to improve the reliability of package source, but I'll let him decide if we want to keep this ticket open or not. @robotblake?

**Comment by jezdez** [comment]
Closing as @marco-c confirmed on IRC that he never saw the issue again. Probably a transient error with the Python package installation in the EMR bootstrap script.
