### ISSUE TITLE
Scheduled job has not run for several days

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/telemetry-analysis-service#385]
The `mreid-telemetry-budget-report` job should run every day, but it seems to have stopped on April 6th, and based on the output of the report, it may have missed a couple of days in early April as well.

I did not receive any failure or timeout notifications, as far as I can tell.

**Comment by mystor** [comment]
My `collect-nightly-background-hang-report-native-stacks` job also should run every day. It has not run successfully since April 6th, and seems to have not run at all since April 8th.

**Comment by marco-c** [comment]
Probably same underlying issue as #326 and #351.

**Comment by rafrombrc** [comment]
Closing as duplicate.
