### ISSUE TITLE
delete / edit buttons in user dash - not clear which job will be affected

### ISSUE THREAD

**Issue by gregglind** [mozilla/telemetry-analysis-service#39]

**Comment by jezdez** [comment]
Please file feature requests in [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Cloud%20Services&component=Metrics%3A%20Pipeline&short_desc=ATMO%20V2%3A%20&blocked=1248688)

**Comment by jezdez** [comment]
Wait, actually this is already filed in [bug 1309227](https://bugzilla.mozilla.org/show_bug.cgi?id=1309227), and will be fixed by #37. Thanks for the report tho!
