### ISSUE TITLE
is my job running? - overview visibility

### ISSUE THREAD

**Issue by gregglind** [mozilla/telemetry-analysis-service#40]
for jobs that I have scheduled.... are they currently running?  Did they ever run?

**Comment by jezdez** [comment]
Please file feature requests in [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Cloud%20Services&component=Metrics%3A%20Pipeline&short_desc=ATMO%20V2%3A%20&blocked=1248688)
