### ISSUE TITLE
Specify performance metrics for instrumentation to support monitoring / notifications

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/telemetry-analysis-service#418]
We need to compile the set of metrics that will provide better visibility into the behavior of various pieces of ATMO functionality (esp scheduled jobs) and then instrument the code (either w statsd calls that we can send to Datadog or log items that will land in ES/Kibana) so we can generate dashboards and possibly notifications.

List of possible metrics (area of concern: `CLUSTER` = on-demand clusters, `SPARKJOB` = scheduled Spark jobs):

- [ ] `CLUSTER` `SPARKJOB` Number of AWS API error responses and which kind (e.g. throttling exception)
- [ ] `CLUSTER` `SPARKJOB` Number of Python errors/exceptions via Sentry (to see code regressions)
- [ ] `CLUSTER` Number of on-demand clusters spun up successfully (to see trends in usage)
- [ ] `CLUSTER` `SPARKJOB` Number of bootstrapping failures during cluster start up (to track issues with EMR bootstrap script)
- [ ] `CLUSTER` Normalized instance hours of clusters (time between creation and finish multiplied by cluster size)
- [ ] `CLUSTER` `SPARKJOB` Time between cluster creation (for both scheduled Spark jobs and on-demand clusters) and its readiness to process the first step (the "bootstrapping time" from the user perspective)
- [ ] `SPARKJOB` the time between the cluster's readiness to process the first step and the time when the cluster is shudown (the "runtime of the notebook code" from the user perspective)
- [ ] `CLUSTER` `SPARKJOB` EMR version used for cluster
- [ ] `CLUSTER` Number of cluster lifetime extensions

**Comment by rafrombrc** [comment]
One metric to track is the number of AWS throttling exceptions we hit.

**Comment by rafrombrc** [comment]
And in fact just notifying on the number of Sentry exceptions would be useful, and would require less work than unwinding the wrapped exceptions in order to differentiate btn the throttling exceptions and other exceptions.

**Comment by jezdez** [comment]
After #264 we now know the creation of cluster/Spark job run (`created_at`/`scheduled_at`), the start of the cluster (`started_at`), the readiness of the cluster (basically when it can process steps, `ready_at`), and the finish time (`finished_at`). We can use that to do two graphs:

1. track the time between spark run creation (`created_at`) to cluster readiness (`ready_at`), which translates to what users perceive as "bootstrapping"

2. track the runtime of the actual job (for Spark jobs), defined as the time between readiness (`ready_at`) and finshed time (`finished_at`)

**Comment by jezdez** [comment]
@rafrombrc I've added a list of metrics to the ticket description above, lemme know if that's the form you expected

**Comment by jezdez** [comment]
Unassigning myself since I think I've done what I can.
