### ISSUE TITLE
Use `select_for_update` in cluster expiration email task

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/telemetry-analysis-service#434]
There's a bit of a race condition [here](https://github.com/mozilla/telemetry-analysis-service/blob/e6fecbe12d09b2e2338ae62f5276b3b2f39b0b65/atmo/clusters/tasks.py#L38) where two tasks could ask for expiring clusters at the same time and start sending emails before they can be marked as sent. We should 1. wrap the whole task in a transaction and 2. use `select_for_update` on the query for active clusters to lock those rows.

**Comment by jezdez** [comment]
Yay!
