### ISSUE TITLE
Failed job gfritzsche-telemetry-probe-scraper

### ISSUE THREAD

**Issue by jezdez** [mozilla/telemetry-analysis-service#443]
A recent run (j-28RZWZITFCJ0N) of gfritzsche-telemetry-probe-scraper has produced these errors that seem to indicate an issue with the notebook or a related service:

```python
!cd $repo_dir && pip install -r requirements.txt && python probe_scraper/runner.py --outdir $output_dir --tempdir $cache_dir
```

    Requirement already satisfied (use --upgrade to upgrade): requests in /mnt/anaconda2/lib/python2.7/site-packages (from -r requirements.txt (line 1))
    Collecting requests_cache (from -r requirements.txt (line 2))
      Downloading requests_cache-0.4.13-py2.py3-none-any.whl
    Requirement already satisfied (use --upgrade to upgrade): pyyaml in /mnt/anaconda2/lib/python2.7/site-packages (from -r requirements.txt (line 3))
    Installing collected packages: requests-cache
    Successfully installed requests-cache-0.4.13
    [33mYou are using pip version 8.1.2, however version 9.0.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.[0m
    Unable to parse whitelist (/home/hadoop/analyses/probe-scraper/probe_scraper/parsers/third_party/histogram-whitelists.json). Assuming all histograms are acceptable.
    

<a lot of extracted were printed here>

    Traceback (most recent call last):
      File "probe_scraper/runner.py", line 93, in <module>
        main(args.tempdir, args.outdir)
      File "probe_scraper/runner.py", line 61, in main
        results = PARSERS[probe_type].parse(paths, details["version"])
      File "/home/hadoop/analyses/probe-scraper/probe_scraper/parsers/histograms.py", line 69, in parse
        parsed_probes = list(histogram_tools.from_files(filenames))
      File "/home/hadoop/analyses/probe-scraper/probe_scraper/parsers/third_party/histogram_tools.py", line 537, in from_files
        yield Histogram(name, definition, strict_type_checks=False)
      File "/home/hadoop/analyses/probe-scraper/probe_scraper/parsers/third_party/histogram_tools.py", line 114, in __init__
        self.verify_attributes(name, definition)
      File "/home/hadoop/analyses/probe-scraper/probe_scraper/parsers/third_party/histogram_tools.py", line 242, in verify_attributes
        lambda allowed_keys: Histogram.check_keys(name, definition, allowed_keys))
      File "/home/hadoop/analyses/probe-scraper/probe_scraper/parsers/third_party/histogram_tools.py", line 40, in table_dispatch
        return body(table[kind])
      File "/home/hadoop/analyses/probe-scraper/probe_scraper/parsers/third_party/histogram_tools.py", line 242, in <lambda>
        lambda allowed_keys: Histogram.check_keys(name, definition, allowed_keys))
      File "/home/hadoop/analyses/probe-scraper/probe_scraper/parsers/third_party/histogram_tools.py", line 388, in check_keys
        raise KeyError, '%s not permitted for %s' % (key, name)
    KeyError: u'record_in_processes not permitted for A11Y_INSTANTIATED_FLAG'

## Upload the output to S3.

```python
# Get access to the S3 connect API.
client = boto3.client('s3', 'us-west-2')
transfer = boto3.s3.transfer.S3Transfer(client)
```

```python
# Copy the files to S3.
for file_name in OUTPUT_FILES:
    source_path = os.path.join(output_dir, file_name)
    key_path = S3_DATA_PATH + file_name
    print "uploading " + file_name + " to s3: " + key_path
    transfer.upload_file(source_path, S3_PUBLIC_BUCKET, key_path)
```

    uploading general.json to s3: probe-scraper/data/general.json

    

    OSErrorTraceback (most recent call last)

    <ipython-input-13-3d665e1944c5> in <module>()
          4     key_path = S3_DATA_PATH + file_name
          5     print "uploading " + file_name + " to s3: " + key_path
    ----> 6     transfer.upload_file(source_path, S3_PUBLIC_BUCKET, key_path)
    

    /mnt/anaconda2/lib/python2.7/site-packages/boto3/s3/transfer.pyc in upload_file(self, filename, bucket, key, callback, extra_args)
        273             filename, bucket, key, extra_args, subscribers)
        274         try:
    --> 275             future.result()
        276         # If a client error was raised, add the backwards compatibility layer
        277         # that raises a S3UploadFailedError. These specific errors were only

    /mnt/anaconda2/lib/python2.7/site-packages/s3transfer/futures.pyc in result(self)
         71             # however if a KeyboardInterrupt is raised we want want to exit
         72             # out of this and propogate the exception.
    ---> 73             return self._coordinator.result()
         74         except KeyboardInterrupt as e:
         75             self.cancel()

    /mnt/anaconda2/lib/python2.7/site-packages/s3transfer/futures.pyc in result(self)
        231         # final result.
        232         if self._exception:
    --> 233             raise self._exception
        234         return self._result
        235 

    OSError: [Errno 2] No such file or directory: '/home/hadoop/analyses/probe_data/general.json'

**Comment by georgf** [comment]
This is one of the fallouts from [bug 1335343](https://bugzilla.mozilla.org/show_bug.cgi?id=1335343).

I know about it and am tracking it in [bug 1363973](https://bugzilla.mozilla.org/show_bug.cgi?id=1363973).
This is lower priority though than fixing the aggregator job and other things.

**Comment by jezdez** [comment]
@georgf Thanks!
