### ISSUE TITLE
Failed job minvid-daily

### ISSUE THREAD

**Issue by jezdez** [mozilla/telemetry-analysis-service#444]
A recent run (j-28OJHGHGMTPEO) failed with:

```
    AnalysisException: u'path s3n://net-mozaws-prod-us-west-2-pipeline-analysis/isegall/minvid_daily/v1/activity_date=20170510 already exists.;'
```

The general gist is that it seems that changes to the ATMO scheduling infrastructure (to fix flakiness) have triggered a second run of the job after it was already run for that day. I'm raising the issue here still to make sure it's known by the owner of the job @ilanasegall.

**Comment by mreid-moz** [comment]
cc @ilanasegall

**Comment by jezdez** [comment]
@mreid-moz Thanks!

**Comment by jezdez** [comment]
@ilanasegall Closing since this was a transient error during the deploy of the new Spark job scheduling system and the job has had successful runs since then.
