### ISSUE TITLE
Failed job daily-export-of-previous-day-oom-crash-data-v1-to-s3

### ISSUE THREAD

**Issue by jezdez** [mozilla/telemetry-analysis-service#446]
A recent run (j-1GDGI7AK4HDOD) failed with:

```
    AnalysisException: u'path s3://net-mozaws-prod-us-west-2-pipeline-analysis/ddurst/crash_stats_oom/v1/submission=2017-05-10 already exists.;'
```

The general gist is that it seems that changes to the ATMO scheduling infrastructure (to fix flakiness) have triggered a second run of the job after it was already run for that day. I'm raising the issue here still to make sure it's known by the owner of the job @ddurst.

**Comment by ddurst** [comment]
Ah, thank you, because when I saw the failure alert, I was very much confused.

**Comment by jezdez** [comment]
@ddurst No problem, I'll revisit the ticket tomorrow again on the next iteration of the job to make sure things work as expected -- and close if so.

**Comment by jezdez** [comment]
@ddurst Closing since this was a transient error during the deploy of the new Spark job scheduling system and the job has had successful runs since then.
