### ISSUE TITLE
Failed job txp-install-uninstall-events

### ISSUE THREAD

**Issue by jezdez** [mozilla/telemetry-analysis-service#447]
A recent run (j-2EGN4BUYRIL9) failed with:

```
    AnalysisException: u'path s3://net-mozaws-prod-us-west-2-pipeline-analysis/ssuh/txp_events/v1/submission_date=20170510 already exists.;'
```

The general gist is that it seems that changes to the ATMO scheduling infrastructure (to fix flakiness) have triggered a second run of the job after it was already run for that day. I'm raising the issue here still to make sure it's known by the owner of the job @sunahsuh.

**Comment by sunahsuh** [comment]
ACK
