### ISSUE TITLE
Failed job txp_snoozetabs

### ISSUE THREAD

**Issue by jezdez** [mozilla/telemetry-analysis-service#449]
A recent run (j-48WJ0ELEGKFU) failed with:

```
    AnalysisException: u'path s3://telemetry-parquet/testpilot/txp_snoozetabs/v2/submission_date=20170510 already exists.;'
```

The general gist is that it seems that changes to the ATMO scheduling infrastructure (to fix flakiness) have triggered a second run of the job after it was already run for that day. I'm raising the issue here still to make sure it's known by the owner of the job @sunahsuh.

**Comment by sunahsuh** [comment]
ACK, thanks for the info :)
