### ISSUE TITLE
Failed job prof-daily

### ISSUE THREAD

**Issue by jezdez** [mozilla/telemetry-analysis-service#451]
A recent run (j-GTKX21W0SJRL) failed with:

```
    Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
    : org.apache.spark.SparkException: Job aborted due to stage failure: Task 57 in stage 102.0 failed 4 times, most recent failure: Lost task 57.3 in stage 102.0 (TID 16061, ip-172-31-15-39.us-west-2.compute.internal): java.io.FileNotFoundException: No such file or directory 's3://telemetry-parquet/harter/cliqz_testpilottest/v1/submission=20170510/part-r-00044-464084f1-f852-48ad-b0a3-8507f8841a61.snappy.parquet'
    It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
```

The general gist is that it seems that changes to the ATMO scheduling infrastructure (to fix flakiness) have triggered a second run of the job after it was already run for that day. I'm raising the issue here still to make sure it's known by the owner of the job @harterrt.

**Comment by harterrt** [comment]
Just to verify my understanding: We consider spawning the second job a bug and not a feature, correct? It looks like the data is there, so the primary job probably succeeded. The only negative side effect seems to be the false alert. 

If that's accurate, does this need to be addressed or can we just let the job complain until we're only spawning one job?

**Comment by jezdez** [comment]
@harterrt Yes, the second spawning is a side effect of us deploying the new scheduling yesterday that has been implemented to prevent duplicate spawning. I know it sounds backward, but this was only related to the deployment since the new scheduling system thought it never had run a job before. I still wanted to raise a ticket with the job owners (hence the other tickets with similar issues) to explain the reasons for the additional alert.

**Comment by harterrt** [comment]
Great, thanks for the extended explanation!
