### ISSUE TITLE
Failed job mreid-telemetry-budget-report

### ISSUE THREAD

**Issue by jezdez** [mozilla/telemetry-analysis-service#452]
A recent run (j-19JJVR94YH6BP) failed with:

```

    TypeErrorTraceback (most recent call last)

    <ipython-input-16-7fa6f622b64b> in <module>()
         38 
         39 if len(errors) > 0:
    ---> 40     send_alert(errors)
         41 else:
         42     print "No errors detected. Huzzah!"


    TypeError: send_alert() takes exactly 2 arguments (1 given)
```

The general gist is that it seems that changes to the ATMO scheduling infrastructure (to fix flakiness) have triggered a second run of the job after it was already run for that day. I'm raising the issue here still to make sure it's known by the owner of the job @mreid-moz.

**Comment by mreid-moz** [comment]
Thanks for raising it. This job will be deprecated as part of [Bug 1370529](https://bugzilla.mozilla.org/show_bug.cgi?id=1370529).  Closing this issue.
