### ISSUE TITLE
Use select_for_update() in more tasks 

### ISSUE THREAD

**Issue by jezdez** [mozilla/telemetry-analysis-service#454]
After #434 I've found a few more spots where this is useful:

- [ ] `atmo.jobs.tasks.send_run_alert_mails`
- [ ] `atmo.jobs.tasks.expire_jobs`
- [ ] `atmo.jobs.tasks.update_jobs_statuses`
- [ ] `atmo.clusters.tasks.deactivate_clusters`
- [ ] `atmo.clusters.tasks.update_master_address`
- [ ] `atmo.clusters.tasks.update_clusters`

@sunahsuh Are you up for this?

**Comment by sunahsuh** [comment]
I can probably get to this later this week

**Comment by jezdez** [comment]
@sunahsuh Cheers, lemme know if something gets in the way.

**Comment by jezdez** [comment]
Closing as @sunahsuh said in #484 that the other tasks are not required to have select_for_update.
