### ISSUE TITLE
Upgrade EMR to v5.5.0 in order to support Zeppelin v0.7.1

### ISSUE THREAD

**Issue by comloo** [mozilla/telemetry-analysis-service#468]
The release of Zeppelin 0.7.1 changed the way data is stored in JSON compared to our EMR version of Zeppelin (0.6.2). It seems like EMR v5.5.0 uses the newer version of Zeppelin, along with the newer versions of some other important dependencies. The following table lists such dependencies along with the version that comes with the different EMR releases.

EMR Version | Spark | Presto | Hadoop | Zeppelin | Hive
-|-|-|-|-|-
5.2.1 (current) and 5.2.2 | 2.0.2 | 0.157.1 | 2.7.3 | 0.6.2 | 2.1.0
5.3.0 | 2.1.0 | 0.157.1 | 2.7.3 | 0.6.2 | 2.1.1
5.4.0 | 2.1.0 | 0.166 | 2.7.3 | 0.7.0 | 2.1.1
5.5.0 | 2.1.0 | 0.170 | 2.7.3 | 0.7.1 | 2.1.1

Before upgrading we need to check to see if v5.5.0 is backwards compatible.
- [X] Spark
- [ ] Presto
- [ ] Hadoop
- [x] Zeppelin
- [ ] Hive

**Comment by jezdez** [comment]
After double checking with @maurodoglio and @comloo I've just enabled 5.5.0 in production as an experimental release (not selected by default) and added an announcement to the top of the page. I suggest to keep this issue open for now while we get feedback from users.
