### ISSUE TITLE
Ascertain how to effectively version EMR scripts

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/telemetry-analysis-service#493]
Currently EMR version management is very ad-hoc and not well managed. We need to figure out how to manage these better. One proposed solution is to move the EMR scripts into the ATMO github repo and tightly couple them with ATMO releases.

**Comment by rafrombrc** [comment]
Blocks #203.

**Comment by robhudson** [comment]
What does "versioning" mean exactly in this context?

**Comment by jezdez** [comment]
@robhudson I think this goes back to a discussion about how the EMR bootstrap scripts are not updated/released with ATMO deploys and have in the past caused issues when they were updated outside the ATMO release process. Moving the EMR bootstrap scripts inside the ATMO repo means there will have to be a review before we can deploy them.

**Comment by rafrombrc** [comment]
We've now got the ability to use separate S3 buckets as the home for the EMR script code with each ATMO deployment (i.e. prod, staging, dev, etc.). There are a bunch of other issues related to the coordination of the EMR code and the ATMO code, but the main problem that this issue was created to capture is solved so we're closing this and will use other issues to track the other pieces.
