### ISSUE TITLE
On 2016-06-16 UTC, job is due next on 2016-06-15 UTC

### ISSUE THREAD

**Issue by marco-c** [mozilla/telemetry-analysis-service#553]
Today, 2016-06-16, one of my jobs was due next on 2016-06-15.

**Comment by robhudson** [comment]
Can you provide the name of the spark job as seen in ATMO?

**Comment by marco-c** [comment]
top-signatures-correlations

**Comment by marco-c** [comment]
I'm seeing this again today (20 July), "It's due next at 2017-07-19 23:41 UTC.".

I'm going to run it manually now, even though I can't know if "the job will finish before its next scheduled run or it may be skipped automatically.".

**Comment by robhudson** [comment]
For @washort ... the `due_at` is part of the redbeat scheduler [here](https://github.com/sibson/redbeat/blob/ccac3e103dc1d83aa3176d807bfc7cb57adfe518/redbeat/schedulers.py#L173).

**Comment by washort** [comment]
I don't see any obvious ways this could occur, so I don't think I can make progress on it without a reproducible example.

**Comment by rafrombrc** [comment]
Closing unless and until this pops up again, hopefully in a reproducible way.

**Comment by jezdez** [comment]
@marco-c Thanks for the report, I've filed #888 instead since I'm not sure if this is the same issue as this.
