### ISSUE TITLE
Spark job should be cancellable from Jupyter notebook

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/telemetry-analysis-service#554]
Currently there is no good way to cancel a running Spark job from Jupyter. We should add support for that to the jupyter-spark extension. (From bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1286859)

**Comment by washort** [comment]
https://github.com/mozilla/jupyter-spark/pull/26

**Comment by mreid-moz** [comment]
Resolved by https://github.com/mozilla/jupyter-spark/pull/34
