### ISSUE TITLE
py4j error, even after updating py4j

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/telemetry-analysis-service#561]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1371012:

In running https://gist.github.com/ddurst/4cdad11ac9c30d340bfe4a5f0d6585aa, I run three routines. The first two, which are nearly identical, ran. The third, which is only slightly different -- and not different at all in how the RDD is accessed (as far as I can tell) -- consistently fails.

I asked frank about this traceback, and he recommended pip installing py4j (which I did), but I got the exact same error.

Because some days had passed since the first two routines were run, I re-ran the first to see if it failed again. It worked fine (took a while, but worked fine).

I expect some sort of user error, but I don't know what it might be at this point.

**Comment by washort** [comment]
bugzilla bug is resolved
