### ISSUE TITLE
Self serve cluster lifetime extension not working

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/telemetry-analysis-service#627]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1382296:

I ran a spark cluster on ATMO with an initial lifetime of 24 hours. About 12 hours in, I used the "extend lifetime" button a few times to push the clusters termination time out by 3 days. However, at the end of the 24 hour initial lifetime the cluster was terminated.

Steps leading to issue:
1) started a spark cluster with 1 node, 24 hour lifetime
2) 12 hours in, used "extend lifetime" button three times (added 72 hours)
3) cluster terminated after only the initial 24 hour period

**Comment by sunahsuh** [comment]
I updated the bugzilla bug with this:
So, according to CloudTrail, it's *not* the prod ATMO instance that's killing the clusters -- the kill request is coming from an old dev instance of ATMO. I'm going to kill that environment (I don't think it's being used anymore -- the code hasn't been updated in nearly a year) and hopefully that fixes the problem.
