### ISSUE TITLE
New cluster appearing twice in ATMO

### ISSUE THREAD

**Issue by comloo** [mozilla/telemetry-analysis-service#658]
<img width="1167" alt="screen shot 2017-08-03 at 10 51 51 am" src="https://user-images.githubusercontent.com/8788060/28913924-f5dcf13c-7839-11e7-8138-7a4464b2396c.png">

Started up a cluster called `pensive-bhabha-1822` after terminating `vigorous-brattain-5318`, and it shows up twice on the home page. After refreshing and clicking around, it remains appearing twice.

**Comment by comloo** [comment]
After the clusters finished bootstrapping, it appears that they are two different clusters, and not the same one that appears twice on the front end.

First one:
<img width="625" alt="screen shot 2017-08-03 at 11 09 34 am" src="https://user-images.githubusercontent.com/8788060/28914524-42f08cd4-783c-11e7-9b35-9a544cda9631.png">

Second one:
<img width="652" alt="screen shot 2017-08-03 at 11 09 22 am" src="https://user-images.githubusercontent.com/8788060/28914530-4751880a-783c-11e7-8774-f6741beaf360.png">

**Comment by rafrombrc** [comment]
Are you still seeing this prob

**Comment by rafrombrc** [comment]
Are you still seeing this problem? If so, are you able to reliably reproduce it? We've not seen it, and aren't sure how to get it to happen.

**Comment by comloo** [comment]
No, I haven't seen this problem since. I wonder if it's got to do with terminating a cluster and starting another up in some time frame...

**Comment by rafrombrc** [comment]
Closing for now until and unless this pops up again.
