### ISSUE TITLE
Zeppelin is broken

### ISSUE THREAD

**Issue by robhudson** [mozilla/telemetry-analysis-service#683]
When launching a cluster and testing the Telemetry tutorial zeppelin notebook there is an error:
`java.lang.IllegalArgumentException: localRepoPath should have a value`

This was a bug that was supposedly fixed upstream in Zeppelin and I was expecting it to be fixed in EMR version 5.8.0 which contains Zeppelin 0.7.2, but the problem still persists.

This bug is to investigate if we are doing something wrong during bootstrapping or if there's anything we can do to get Zeppelin working.

**Comment by whd** [comment]
This was fixed by https://github.com/mozilla/emr-bootstrap-spark/pull/115. I tested EMR 5.8.0 and 5.2.1 and both worked.
