### ISSUE TITLE
Add EMR 5.9.0 release

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/telemetry-analysis-service#847]
Please add the [5.9.0](http://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-whatsnew.html) EMR release as an experimental option when launching clusters in AMO.

**Comment by robhudson** [comment]
Added EMR 5.9.0 as experimental. Updated 5.8.0 to be active and no longer experimental. Current active releases are now: 5.8.0, 5.2.1, and 5.0.0. I think we should deprecate some of these older ones.
