### ISSUE TITLE
Add OIDC claim verification for LDAP groups

### ISSUE THREAD

**Issue by jezdez** [mozilla/telemetry-analysis-service#978]

**Comment by jezdez** [comment]
#982 takes care of the ATMO side and uses the changes done in https://github.com/mozilla-services/cloudops-deployment/pull/1514.

PS: https://github.com/mozilla/redash/pull/311 is the PR for STMO/Redash.

**Comment by robotblake** [comment]
Clarification that this does not require the changes in https://github.com/mozilla-services/cloudops-deployment/pull/1514 as we're talking to Auth0 directly in ATMO.

**Comment by jezdez** [comment]
@robotblake You're right, updating my comment from above.
